version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./web-project:/web-project
      - ./conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    networks:
      - nginxphp

  php:
    image: php:7.1.11-fpm-alpine
    volumes:
      - ./web-project:/web-project
    expose:
      - 9000
    networks:
      - nginxphp

  adminer:
    image: adminer
    ports:
      - 8080:8080

networks:
  nginxphp:
volumes:
  my-db:
