version: '3.7'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8181:80
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
    - php

    depends_on:
      - db
    links:
      - db:db
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./webapp:/webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
