version: '3'

services:

     db:
        image: mariadb
        ports: 
            - 3307:3306
        volumes:
            - dbvol:/var/lib/mysql
        environment: 
            MYSQL_USER: dbuser,
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: appdb
     web:
       image: nginx:alpine
       ports:
           - "80:80"
       volumes:
           - ./web-project:/web-project
           - ./conf.d:/etc/nginx/conf.d
           - /etc/localtime:/etc/localtime
       networks:
           - nginxphp

     php:
       image: php:7.1.11-fpm-alpine
       volumes:
           - ./web-project:/web-project
       expose:
           - 9000
       networks:
           - nginxphp

     adminer:
        image: adminer
        ports:
            - 8080:8080
    
networks:
     nginxphp:
volumes:
    dbvol: {}