version: '3'

services:
  db:
<<<<<<< HEAD
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8181:80
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./webapp:/webapp
      - ./site.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - db
    links:
      - db:db
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
      - ./webapp:/webapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
=======
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./web-project:/web-project
      - ./conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    networks:
      - nginxphp

  php:
    image: php:7.1.11-fpm-alpine
    volumes:
      - ./web-project:/web-project
    expose:
      - 9000
    networks:
      - nginxphp

  adminer:
    image: adminer
    ports:
      - 8080:8080

networks:
  nginxphp:
volumes:
  my-db:
>>>>>>> origin/master
